#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="nvim,zsh,alacritty,sc-im"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles-work
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
